version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-db
    user: root
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
      - ./qdrant_cache:/root/.cache
      - ./hf_cache:/root/.cache/huggingface
    environment:
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      - HF_HOME=/root/.cache/huggingface